### ISSUE TITLE
Card Images

### ISSUE THREAD

**Issue by RaphaLopes** [Spiderpig86/Cirrus#1]
Hello, lovely framework, thanks for making it available for free :)
However, I can't manage to make Card Images to appear correctly.
Don't know what I'm doing wrong, I tried lots of different ways, using the examples on the site, copying directly from your site's HTML...
I tried importing the full file and only the card component, both ways I failed to make it work.
Here's my HTML:

`<div class="section-destaques-container">

			
			<div class="card">
				<div class="card-container">
				<div class="card-image" style="background-image: url(assets/images/rocket-background-in-flat-design_1302-2440.jpg)"></div>

					<div class="title-container">
						<p class="title">Deer</p><span class="subtitle">By Teddy Kelley</span>
					</div>
				</div>
				<div class="content">
					<p>Destaque 1</p>
				</div>
				<div class="action-bar center">
					<button class="btn">SHARE</button>
					<button class="btn">LEARN MORE</button>
				</div>
			</div>
			
			
			<div class="card">
				<div class="card-container">
				<div class="card-image" style="background-image: url(assets/images/rocket-background-in-flat-design_1302-2440.jpg)"></div>

					<div class="title-container">
						<p class="title">Deer</p><span class="subtitle">By Teddy Kelley</span>
					</div>
				</div>
				<div class="content">
					<p>Destaque 2</p>
				</div>
				<div class="action-bar center">
					<button class="btn">SHARE</button>
					<button class="btn">LEARN MORE</button>
				</div>
			</div>

			
			<div class="card">
				<div class="card-container">
				<div class="card-image" style="background-image: url(assets/images/rocket-background-in-flat-design_1302-2440.jpg)"></div>

					<div class="title-container">
						<p class="title">Deer</p><span class="subtitle">By Teddy Kelley</span>
					</div>
				</div>
				<div class="content">
					<p>Destaque 3</p>
				</div>
				<div class="action-bar center">
					<button class="btn">SHARE</button>
					<button class="btn">LEARN MORE</button>
				</div>
			</div>

			
			<div class="card">
				<div class="card-container">
				<div class="card-image" style="background-image: url(assets/images/rocket-background-in-flat-design_1302-2440.jpg)"></div>

					<div class="title-container">
						<p class="title">Deer</p><span class="subtitle">By Teddy Kelley</span>
					</div>
				</div>
				<div class="content">
					<p>Destaque 4</p>
				</div>
				<div class="action-bar center">
					<button class="btn">SHARE</button>
					<button class="btn">LEARN MORE</button>
				</div>
			</div>

		</div>`

The image is a local image, however I already tried using the dynamic images from your website as well:
- background-image: url(https://unsplash.it/640/480?random&blur)"
- https://source.unsplash.com/random/640x480

**Comment by Spiderpig86** [comment]
Hey and thanks for checking out the framework. I have experienced this issue before and I think the way to fix it is to remove `<!DOCTYPE html>` from the top of the page. I will try to see if there is a workaround where it does work with the declaration, but for now removing it seems like the simple solution.

**Comment by RaphaLopes** [comment]
Hey friend, thanks for your reply.
Worked like a charm, thank you so much!
Will be following the development of Cirrus, great work so far, congrats and thank you! :)
By the way, I always used unsplash but I didn't know about that feature for retrieving random images. Very nice.
