### ISSUE TITLE
Missing colors key in configuration extend examples

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#108]
**Describe the issue with the documentation**
Missing `colors: ()` in the configuration extend examples

**Issue Location (if incorrect/inconsistent information)**
 https://cirrus-ui.netlify.app/getting-started/configuration#extend
 https://cirrus-ui.netlify.app/getting-started/configuration#clearing-defaults

URL:
Screenshots:
![image](https://user-images.githubusercontent.com/7860859/164112101-04bb03dd-1ceb-4170-bd2b-73fe67c860d7.png)

Incorrect text/code/example:
```scss
@use "cirrus-ui/src/cirrus-ext" as * with (
    $config: (
        extend: (
            semantic: (
                'primary': #0066FF,
                'midnight': '#121062',
            )
        )
    )
);
```

What it should say/display instead:
```scss
@use "cirrus-ui/src/cirrus-ext" as * with (
  $config: (
    extend: (
      colors: (
        semantic: (
          "primary": #0066ff,
          "midnight": "#121062",
        ),
      ),
    ),
  )
);

```

**Comment by Spiderpig86** [comment]
Thanks for the report! Fixed the docs, closing.
