### ISSUE TITLE
Implementation for ReactJS/React Native

### ISSUE THREAD

**Issue by DouglasRenato** [Spiderpig86/Cirrus#11]
Hello, these days I've been looking at Cirrus and I have really enjoyed the components and simplicity.

I'm not sure if I'm wrong, but it looks like it uses JQuery in some parts of the code. And this may not work very well with ReactJs, because JQuery directly manipulates the DOM, since React uses a virtual DOM.

**I would like to know what components use JQuery and if you are thinking about creating React components of the framework.**

Thank you, keep up the good work.

**Comment by Spiderpig86** [comment]
I'll update the README in a bit to specify which components rely on JQuery. Components like the header should work fine without the JQuery if you are able to replicate that functionality in Angular, React, or any other framework by toggling the class based on a local variable (boolean). I have done it with Angular before, so it should be possible in React as well.
