### ISSUE TITLE
Remove CSS vendor prefixes from the .scss source

### ISSUE THREAD

**Issue by blackbaud-pacific** [Spiderpig86/Cirrus#119]
It'd be great if you could remove the few remaining vendor prefixes (there's not many) in the sass source and let the end-user add these using an autoprefixer during build if needed. 

I think this would just be a cleaner solution...as an example: 
using Parcel as a build tool breaks the .form-group display. 

**To Reproduce**
Compile CSS using Parcel (e.g. yarn start) 
`display: flex;
display: -ms-flexbox;`
is compiled to
`display: -ms-flexbox;`
...removing the original flex declaration. 
(Easily fixed of course by using a utility class or overriding the style in index.scss.)

This is default Parcel behaviour and isn't a bug with Cirrus, but this problem could be avoided by leaving vendor-prefixing to the build tools.

Cheers :-)

**Comment by Spiderpig86** [comment]
Thanks for reporting this! I will take a look and see which prefixes are still needed and which are not using http://caniuse.com/. If there ends up being a few prefixes that are required, then I can write off the usage. If there are still a substantial number of browsers unable to support some CSS feature, then I am considering adding a flag to toggle vendor prefixes.

**Comment by Spiderpig86** [comment]
I have removed a sufficient amount of vendor prefixing except for 1 (this is done over a few commits, eff211e6b008f0cb3289d51eb338913e0ffaa8a3 being the last one). I believe there shouldn't be any issues moving forward with using Parcel as the remaining ones are required to render pages correctly.
