### ISSUE TITLE
[Documentation] Vertical label divider: invisible example

### ISSUE THREAD

**Issue by clembu** [Spiderpig86/Cirrus#165]
**Describe the issue with the documentation**
The vertical label divider in https://www.cirrus-ui.com/layout/divider#basics is effectively invisible, but for the label itself.
Its height is either 0 or auto, because the class `h-100pp` is applied to it, which should be `h-100p`.

**Issue Location (if incorrect/inconsistent information)**
https://github.com/Spiderpig86/Cirrus/blob/ca44b55d16ca47e94a30ea8e1635c87aa54d75c8/cirrus-docs-next/src/layout/divider/index.tsx#L95
https://github.com/Spiderpig86/Cirrus/blob/ca44b55d16ca47e94a30ea8e1635c87aa54d75c8/cirrus-docs-next/src/layout/divider/index.tsx#L100

URL: https://www.cirrus-ui.com/layout/divider#basics
Screenshots:
![image](https://user-images.githubusercontent.com/13928490/230077366-cf5461a2-ae27-419d-8c75-d0fe69ee649b.png)

What it should say/display instead:
![image](https://user-images.githubusercontent.com/13928490/230077872-155cc09b-2893-4d8a-aadb-580164a99252.png)

**Comment by Spiderpig86** [comment]
I will be closing this issue since I merged your PR to fix it. Thanks for your contribution!
