### ISSUE TITLE
animations documentation seems to be broken

### ISSUE THREAD

**Issue by ristiisa** [Spiderpig86/Cirrus#172]
**Describe the bug**
Non of the animations work https://cirrus-ui.netlify.app/animations/animated-styles
Seems related but the following fails GET https://cirrus-ui.netlify.app/animations/sw.js -> 404

**Comment by Spiderpig86** [comment]
Hey @ristiisa. I am not able to reproduce it on my end. Could you share a GIF of this if possible? Thanks!

**Comment by ristiisa** [comment]
https://github.com/Spiderpig86/Cirrus/assets/514571/4e4ce783-89e6-4ed1-a59b-6ad620e4a48d

**Comment by ristiisa** [comment]
Android, windows and macos firefox, chrome and safari... all have the same behaviour. Only platform that seems to work for me is  ios

**Comment by Spiderpig86** [comment]
That is strange. Just out of curiosity, do you have settings enabled for reduced motion?

**Comment by Spiderpig86** [comment]
I just tested with the reduced motions flag on and I was able to reproduce the issue you see above. Is there something that may be forcing that behavior on your machines?

![image](https://github.com/Spiderpig86/Cirrus/assets/2801187/2f6fd206-118b-4559-aa55-dc873ac65f47)

**Comment by ristiisa** [comment]
I referenced this to 
https://stackoverflow.com/questions/59708960/how-do-i-change-the-prefers-reduced-motion-setting-in-browsers

It seems that on my second windows machine the animations play out fine and that machine has "show animations" enabled where the other where the animations don't play has this setting disabled.

Both my macs have reduced motion enabled (I think by default as don't remember explicitly enabling them).

https://github.com/Spiderpig86/Cirrus/assets/514571/fe2d9ae2-c3f9-4506-9f7f-3f84a5b3bbb4

Is this intended behaviour?

**Comment by Spiderpig86** [comment]
Ah yes that would explain why the animations are not working. Glad we have found the culprit :)
