### ISSUE TITLE
accessibility issue with the Header

### ISSUE THREAD

**Issue by Ennoriel** [Spiderpig86/Cirrus#186]
**Describe the bug**
The documentation displays accessibility issues in the [Header doc](https://www.cirrus-ui.com/layout/header#basics):
- the role `menu-item` does not exist and should be replaced with `menuitem`
- from what I understand, to make the menu burger button work, we need to add a click event listener to the `.header-btn` class `div` but it's definitely not recomanded, it would require a role `button`, tabindex... A button would be preferable but breaks the style.
- The accessible pattern for custom menus can be seen here: https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

**To Reproduce**
The documentation displays accessibility issues in the [Header doc](https://www.cirrus-ui.com/layout/header#basics):

**Comment by rimjhp-06** [comment]
Hi,
Can you assign this to me?

**Comment by Spiderpig86** [comment]
Closing since this has been resolved
