### ISSUE TITLE
The italics class is not working

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#192]
The "Italics" example under https://www.cirrus-ui.com/fonts/text-elements does not work. I tried it on my own page and it is not working either:

```
<h5>Italics</h5>
<p class="italics">The quick brown fox jumps over the lazy dog.</p>
```

**Comment by Spiderpig86** [comment]
Ack will take a look

**Comment by Spiderpig86** [comment]
Looks like this class was removed in version 0.6.0. I think the decision was that we can just use `<i>` to achieve the same effect.

**Comment by zemian** [comment]
Thanks for the update. I did notice there are few other examples is the same such as `<b>` etc. But I personally prefer to be to add CSS styling rather than adding extra tag to change text styling. What's the benefit of using explicit `<i>`?

**Comment by Spiderpig86** [comment]
After reviewing solutions offered today, seems like a class that can style text as italicized has its benefits. I will be adding this into 0.7.2.
