### ISSUE TITLE
Inconsistent Tag just by switching color

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#193]
```
            <div class="tag tag--black">Dark</div>
            <div class="tag tag--primary">Primary</div>
```
I noticed the mouse pointer changed to hand (as if it is clickable) on "Primary", but the "Dark" doesn't. Why the inconsistency? Why a tag needs to be clickable?

You can see these in doc page as well: https://www.cirrus-ui.com/elements/tags

**Comment by Spiderpig86** [comment]
This will be fixed in 0.7.2.
