### ISSUE TITLE
How to stop animation on resizing textarea input?

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#194]
Hi,

Animation is an awesome thing on it's own, but only when one needs it. For those who does not need it, it is an annoyance and distraction. Example, for the textarea input (https://www.cirrus-ui.com/forms/inputs), if I were to resize it, it is slow because of the animation. How do I disable this? It would be good to default no animation, and let user uses an utility class to add it only as needed.

**Comment by Spiderpig86** [comment]
You would need to add new CSS to override that behavior for whatever text element you want to change. For example:

```css
input {
  transition: box-shadow 0.3s !important;
}
```

**Comment by Spiderpig86** [comment]
I have introduced a fix for 0.7.2.
