### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by RaphaLopes** [Spiderpig86/Cirrus#2]
Hello, how are you?

I would like to know if modals are ready to use, I can see there's some classes already built, however there's no info in the documentation. I tried using them, but I don't know exactly the correct structure and hierarchy of classes. Big fan of this project, thank you!

**Comment by RaphaLopes** [comment]
Nevermind, I just saw I new page you added with modal components documentation. Thank you so much :) Keep it up, awesome project ;)

**Comment by Spiderpig86** [comment]
Thank you.
More documentation is on its way. Development on this may be slower this time around.
