### ISSUE TITLE
How to disable the pink border highlight in Accordion?

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#200]
Hi, How do I disable the red pink box highlighted on the title on accordion when clicked?

An accordion will expand on the content so user already has the attention already (and we have the arrow to indicate state), so having this pink rectangle box is kinda of intrusive at best and not so pretty looking at worse. Just my opinion though. :)

![image](https://github.com/Spiderpig86/Cirrus/assets/22258832/8213f17f-f18d-4df3-84b0-dd4a5b09d3bc)

**Comment by MacFJA** [comment]
To remove the focus indicator:
```html
<style>
    summary:focus { box-shadow: none }
</style>
```

---

IMO, the focus indicator should not be removed: without it you don't know on which accordion item you are, so keyboard navigation is very hard
(you can change the focused accordion item with <kbd>tab</kbd>, and open/close it with <kbd>space</kbd>)

**Comment by Spiderpig86** [comment]
I second the accessibility concerns here. I have updated the outline to follow the default browser styling to help out. b16448501295d758ea17bbbe7e816334afb0fc0b
