### ISSUE TITLE
Frontpage demo card with progressbar is not displaying correctly

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#204]
On the front page of https://www.cirrus-ui.com/, there is a section that show cases few components examples. One of them has card view with many progressbars as stat. When viewed in a Desktop, it is not displayed correctly (the progressbars are overlapping the labels).

Under 

> Or if you do want to start from scatch, build and extend from existing components to fit your use cases.

![image](https://github.com/Spiderpig86/Cirrus/assets/22258832/c1e377e6-d38f-4700-8636-90e95a0414ec)

However if you change the view size to smaller, it stacked the components to larger viewing space, then it looks fine:

![image](https://github.com/Spiderpig86/Cirrus/assets/22258832/65b9732c-3729-438d-9f89-3329a3c27cd8)

**Comment by Spiderpig86** [comment]
This has been fixed in 2b884d079ab9fbc41ae9454b2a0d217b5f9dc1b0
