### ISSUE TITLE
Inline code breaks with an empty text background

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#206]
The following produced a extra background that seems broken:

```
<div class="w-32">
  <p class="lead">To print message on Console, you would use <code>console.log("Hello");</code></p>
</div>
```
![image](https://github.com/Spiderpig86/Cirrus/assets/22258832/8a126648-4a9b-4d3c-9b5d-f182439aa7c6)

**Comment by Spiderpig86** [comment]
I have added a fix for this for 0.7.2.
![image](https://github.com/Spiderpig86/Cirrus/assets/2801187/e4250f93-9dd0-479e-82c5-82ef23d19022)
