### ISSUE TITLE
A `list-dropdown` flash the hidden menu briefly

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#207]
I am not sure if just me, or I see hidden part of dropdown list displayed briefly (flash) then it is hidden.

Create `list-dropdown` like this, and then simply hit F5 to refresh the page, I see the hidden menu getting flashed.

```

            <div class="list-dropdown">
                <div class="btn-group">
                    <button class="btn-primary">Dropdown</button>
                    <button class="btn-primary btn--sm btn-dropdown"><i class="fa fa-wrapper fa-caret-down" aria-hidden="true"></i>
                    </button>
                    <ul class="menu">
                        <li class="menu-item"><a href="!#">Google Chrome</a></li>
                        <li class="menu-item selected"><a href="!#">Firefox</a></li>
                        <li class="menu-item"><a href="!#">Polarity</a></li>
                    </ul>
                </div>
            </div>
```

**Comment by zemian** [comment]
BTW, why not name the class `dropdown-list` instead of `list-dropdown`? It sounds backward.

**Comment by Spiderpig86** [comment]
Will take a look since I can confirm this.

> BTW, why not name the class `dropdown-list` instead of `list-dropdown`? It sounds backward.

It follows the convention of `<element>-<sub property>`. In this case, it follows the same way we name `btn-primary`. Both these preceded updates to follow a more BEM like naming convention like `btn--sm`.

**Comment by Spiderpig86** [comment]
Closing since this has been resolved.
