### ISSUE TITLE
heads up

### ISSUE THREAD

**Issue by SiteSplat** [Spiderpig86/Cirrus#21]
code leads to a 404:
https://spiderpig86.github.io/Cirrus/docs/code

and the tabs example are not working ;-)

Great framework! keep it up.

**Comment by Spiderpig86** [comment]
Thanks for the report! I must've brushed past that not working. I'll get to it soon.

**Comment by Spiderpig86** [comment]
Closing since it was fixed in 0.6.0 launch.
