### ISSUE TITLE
Btn class on Link is not working with "-primary" suffix

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#214]
This works fine:

```
<a class="btn" target="_blank" href="https://google.com">TEST</a>
```

But this failed:

```
<a class="btn-primary" target="_blank" **href="https://google.com">TEST</a>**
```

**Comment by MacFJA** [comment]
The class `btn` is required on `<a>` tag (cf. [documentation](https://www.cirrus-ui.com/buttons/basics))

The correct code is:
```html
<a class="btn btn-primary" target="_blank" href="https://google.com">TEST</a>
```

**Comment by zemian** [comment]
Ah okay got it. However I have to point out that this is inconsistent compare to <input> or <button> Both of these does not require separate "btn" but only <a> requires it? Please consider making them consistent would be helpful.

**Comment by Spiderpig86** [comment]
The only exceptions that don't need the `btn` class are `<button>` and `<input type="submit">` since having that is redundant. We know the intention is that they would be buttons. All other tags like `<div>` or `<a>` will require `btn` to be specified.
