### ISSUE TITLE
Input range control improvements

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#217]
1. The min and max value does not push the thumb circle to the end. This is confusing as visual indicator. Please fix so it goes all the way to the end.
2. When using the slider, the highlighted box is very distracting. Please consider removing it.

![image](https://github.com/Spiderpig86/Cirrus/assets/22258832/422bbfe2-0a47-43d8-b56b-281d35be45a2)

**Comment by MacFJA** [comment]
As a quick and temporary fix you can add this:
```html
<style>
    input[type=range] { padding-inline: 0 !important; }
    input[type=range]:focus { box-shadow: none !important }
</style>
```

**Comment by Spiderpig86** [comment]
Has been resolved with the commit mentioned above
