### ISSUE TITLE
Reference in Placeholder example in documentation

### ISSUE THREAD

**Issue by KAVA-Leigh** [Spiderpig86/Cirrus#22]
Hi there, 
Just a heads up that this line in the documentation 'Placeholder' example appears to have a very small error;

`<div class="placeholder-commands ucenter">`

Should be; 

`<div class="placeholder-commands u-center">`

keep up the great work !

**Comment by Spiderpig86** [comment]
Thanks for the update! Will fix this soon when I get the chance.

**Comment by Spiderpig86** [comment]
This has been fixed.
