### ISSUE TITLE
[Feature] Dark Mode option?

### ISSUE THREAD

**Issue by StupidRepo** [Spiderpig86/Cirrus#272]
I would love if there is a way to enable a dark mode theme, kind of similar to how Bootstrap does it.
e.g. Using Bootstrap, adding `data-bs-theme="dark"` to the `html` tag makes the whole page becomes nice and dark.

Thanks in advance!

**Comment by Spiderpig86** [comment]
The good news is that dark mode support via classes like `dark:text-white` is coming. https://github.com/Spiderpig86/Cirrus/blob/master/src/internal/_generator_v2.scss#L26

However, I have no plans to support switching to a darker color palette for all page elements with a single attribute.

**Comment by Spiderpig86** [comment]
Probably late on providing an update here, but the `dark:` pseudo-selector is now supported for certain utility classes for the dark color scheme on versions 0.8.0 and above.
