### ISSUE TITLE
header-brand class taking all the available space in old browsers (firefox 36)

### ISSUE THREAD

**Issue by RaphaLopes** [Spiderpig86/Cirrus#3]
Hi friend, how are you?

Do you know why the 'header-brand' class take all the available width on old browsers like the firefox 36, which ultimately causes  the nav-items to go down? Please check these screenshots so you can better understand:

Updated Chrome 
![chrome](https://user-images.githubusercontent.com/14355419/36690982-bfa5ed36-1b12-11e8-83a1-2a8fdc3da7ad.png)

Firefox 36
![firefox36](https://user-images.githubusercontent.com/14355419/36690986-c007a0e4-1b12-11e8-946d-6f70d5d6cd9a.png)

I know this issue is caused by some kind of unknown css property to old browsers (cause it works perfectly on Chrome and newer firefox versions), but I would appreciate if you can point me in the right direction cause unfortunately people here in the company still uses old browsers...

I appreciate, thanks for your time.

**Comment by Spiderpig86** [comment]
I'll definitely try to look into this. Most likely it has to be because of the update to the `header` classes when 0.5.3 was released. I may work on a fallback to the old header styles once I get the time.
