### ISSUE TITLE
wordpress  menu walker

### ISSUE THREAD

**Issue by BAProductions** [Spiderpig86/Cirrus#304]
**Describe the issue with the documentation**
A clear and concise description of what you want to change with the documentation. Is something inaccurate? Is it missing information/inconsistent? Would you like to provide a new entry to the docs?

**Issue Location (if incorrect/inconsistent information)**

URL:
Screenshots:

Incorrect text/code/example:

What it should say/display instead:

**New Addition (if adding new documentation)**

*Everything here would preferably be formatted in Markdown. Try to include working examples with code, table contents, and concise descriptions.*

**Comment by Spiderpig86** [comment]
Hey there. Since this issue lacks sufficient context, I will be closing it for now.
