### ISSUE TITLE
Gulp issue

### ISSUE THREAD

**Issue by fmatignon** [Spiderpig86/Cirrus#35]
Hi! I'm quite new to programming and i'm trying to choose a css framework to work with. While trying to set up a new project using Cirrus, I created a new folder and ran `npm install` and got

`up to date in 0.477s`
`found 0 vulnerabilities`

then I ran `npm i cirrus-ui` and got 
`+ cirrus-ui@0.5.5`
` added 22 packages from 56 contributors and audited 22 packages in 3.479s`
`found 0 vulnerabilities`
 
last, ran `npm i gulp` and got
`+ gulp@4.0.2`
`added 355 packages from 219 contributors and audited 6604 packages in 18.534s`
`3 packages are looking for funding`
  `run npm fund for details`
`found 0 vulnerabilities`

but whenever I try to run gulp watch / compile / minify in the node_modules\cirrus-ui folder  I get 
`Error: Cannot find module 'gulp-load-plugins'

Could you explain to me what would be the correct steps to set up a cirrus project and get gulp up and running with it? I figure out it shouldn't be too hard and i'm probably doing something wrong, though I honestly don't have a clue on how gulp works.

**Comment by Spiderpig86** [comment]
Hi there!

Thanks for checking out Cirrus! You can use `cirrus-ui` directly without having to install `gulp`. Gulp is just a dependency to build Cirrus into its combined and minified versions by running `gulp` from the project's root directory.

The error you get is from `gulp-load-plugins` not being installed. Just run `npm i gulp-load-plugins --save-dev` to fix it.

To use Cirrus in your web project, I recommend going through the [Jumpstart guide](https://spiderpig86.github.io/Cirrus/docs/start/) for Cirrus on how to get it setup. Hope this helps.

**Comment by fmatignon** [comment]
Thank you! Since the source files already contain the gulpfile, I wanted to be able to set it up with browsersync for auto-compiling and reloading. I'll check the jumpstart guide. Keep up the good work!
