### ISSUE TITLE
.fluid-container commented out in latest version?

### ISSUE THREAD

**Issue by DynamicArray** [Spiderpig86/Cirrus#36]
Was it intentional to comment out the various .fluid-container classes?

Line 293 onwards of layout.css is missing closing comment tag, meaning none of those classes get into the minified version.

Thanks for your work on this.

**Comment by Spiderpig86** [comment]
Hi,

Thanks for checking out the framework. The `fluid-container` class has been deprecated in [0.5.5](https://github.com/Spiderpig86/Cirrus/commit/7cdfb56a150b7727245c7513339c5ad33987e812) since using the `row` now achieves the same effect.
