### ISSUE TITLE
Missing documentation for header

### ISSUE THREAD

**Issue by dector** [Spiderpig86/Cirrus#39]
Would be nice to have documentation how to build navbar

**Comment by Spiderpig86** [comment]
I believe this is what you are looking for. https://spiderpig86.github.io/Cirrus/docs/header/

**Comment by dector** [comment]
Thanks! That's what I'm looking for. Coudn't find it on Documentation page. But now I see it in the footer. :smiley:

**Comment by Spiderpig86** [comment]
No worries, I'm working on revamping the docs for the next version when I have time. Things can be a bit hard to find.
