### ISSUE TITLE
Website has slightly different look in Firefox and Chromium

### ISSUE THREAD

**Issue by dector** [Spiderpig86/Cirrus#40]
_First, thanks for such great css framework. Personally I find it `simplicity`-`beauty`-`lots of functionaly` combination very attractive!_

**Describe the bug**
- Font sizes are a bit different: they are a bit bigger in Chromium. Scale is 100% in both browsers.

**To Reproduce**
- Open [Cirrus website](https://spiderpig86.github.io/Cirrus/) in Firefox 78 and Chromium 80.
<details><summary>Firefox (2 MB!)</summary>
<img src="https://user-images.githubusercontent.com/265872/86012351-eb781980-ba2e-11ea-8e52-803e9b536bee.png" />
</details>
<details><summary>Chromium (2 MB!)</summary>
<img src="https://user-images.githubusercontent.com/265872/86012386-f3d05480-ba2e-11ea-9d55-c24f56731142.png" />
</details>

**Comment by Spiderpig86** [comment]
Hi @dector!

:tada: Thanks for taking a look at the framework! I have briefly looked into the issue and tested with the major browsers I had. The font scaling is consistent across machines/browsers. Seems like the Chromium font rendering is larger than it should be. Could it be a Chromium 80 issue?

**Machine/Browsers**
- OSX Mojave: Firefox 78/Chrome 81
- Windows 10: Firefox 77/Chrome 83/Edge 84
