### ISSUE TITLE
Default background is not solid

### ISSUE THREAD

**Issue by dector** [Spiderpig86/Cirrus#41]
**Describe the bug**
If user has overridden page background color in browser (e.g. not `#fff`) - web page looses text-background contrast.

**To Reproduce**
- Open Firefox.
- Open Preferences.
- Scroll to "Fonts and Colors".
- Press "Colors...".
- Set background color to something grayish (e.g. `#DADFE8`).
- Open [Cirrus website](https://spiderpig86.github.io/Cirrus/).
- Background is not white now and text is not that much readable on darker background.

<details><summary>Show me! (2MB)</summary>
<img src="https://user-images.githubusercontent.com/265872/86013564-5a09a700-ba30-11ea-81de-269b5723cf94.png" />
</details>

**Comment by Spiderpig86** [comment]
Good catch! Will work on it soon.

**Comment by Spiderpig86** [comment]
Issue resolved 🎉 .
