### ISSUE TITLE
[Question] How to use responsive columns?

### ISSUE THREAD

**Issue by stephannv** [Spiderpig86/Cirrus#42]
Hello, a noobie question: How use [breakpoints](https://spiderpig86.github.io/Cirrus/docs/utils/#breakpoints) classes on columns? 
I'm looking for something like `.col-sm-12 .col-md-8 .col-lg-4`

**Comment by Spiderpig86** [comment]
Hi,

This is currently a feature I'm working on to be added in 0.5.6. https://github.com/Spiderpig86/Cirrus/projects/4#card-39457956

**Comment by stephannv** [comment]
Oh, thanks. This explain why `col-12-mobile` isn`t working hahaha.

Great framework! Keep it up.
