### ISSUE TITLE
Issues with header

### ISSUE THREAD

**Issue by niutech** [Spiderpig86/Cirrus#45]
There are two issues with the header:

1. The Join button has too much padding, because there is `<a>` inside `<button>`:
![Join button](https://user-images.githubusercontent.com/384997/96188778-97dafe80-0f3f-11eb-9a3b-c75b9c03cb01.png)
2. The dropdown menu is moved to the left, because `.nav-link` does not have `position: relative;`: 
![dropdown menu](https://user-images.githubusercontent.com/384997/96189096-29e30700-0f40-11eb-9958-71540e76903a.png)

**Comment by Spiderpig86** [comment]
Hi,

Thanks for pointing this out! I believe this should be rectified in 0.6.0. It isn't officially released yet, but you can try it out by using some of the [builds](https://github.com/Spiderpig86/Cirrus/tree/master/dist).
