### ISSUE TITLE
hover <a> with btn class will make text become blue

### ISSUE THREAD

**Issue by hurtsky** [Spiderpig86/Cirrus#46]
**Describe the bug**
Add `btn` class to `<a>` during hover will make text color become blue.

**Expected result**
the behavior should be like `<button>` with btn class during hover should not make the text color become blue.

**Comment by Spiderpig86** [comment]
Thanks for the report! I'll quickly add the fix. For future reference, I highly recommend separating the link from the button if possible:

```html
    <div class="u-center">
        <a href="#"><button>Test</button></a>
    </div>
```

This way, you get the link behavior and the full styling of the button.

**Comment by hurtsky** [comment]
@Spiderpig86 
```
<div class="u-center">
        <a href="#"><button>Test</button></a>
    </div>
```
i did use this way, but if i assign disabled at `button` the `a` still able to be press. i believe the `a` should have its own `btn` class

**Comment by Spiderpig86** [comment]
I closed early since I am rolling out the fix very soon. It will officially be in the 0.6.0 release, but you can try it out by using the builds inside the `dist` folder. I also disabled all pointer events for buttons with `disabled`.

**Comment by hurtsky** [comment]
@Spiderpig86 thank you so much, from what I can see, if using `<button>` inside `<a>` the button disabled, but the `<a>` still able to click if you point the mouse under outside a bit from button interface.

**Comment by Spiderpig86** [comment]
Unfortunately, if a button is embedded inside `<a>`, I think you can use the `.u-disabled` class starting with 0.6.0. According to the HTML spec, there is no disabled option for `<a>`, so the closest thing would probably be the class in the next update -- which is coming very soon (~1 week or less).
