### ISSUE TITLE
Classnames harmonization

### ISSUE THREAD

**Issue by Aaarrrgggh** [Spiderpig86/Cirrus#51]
Hi,

I would suggest for the next version to harmonize class names for some components. For example, for cards, we have : card, card-title, content, card-footer, action-bar. It could be: card, card__title, card__content, card__footer, card__action according to BEM specifications. However, it is used perfectly for tiles or frames. 

Alexander

**Comment by Spiderpig86** [comment]
Hi,

I agree with this. Cards are definitely one of the components that existed since the start of this framework and need to be updated. Again, this will be added to the 0.6.1 roadmap.

**Comment by Aaarrrgggh** [comment]
Thanks for your answer!

**Comment by Spiderpig86** [comment]
Resolved with release of 0.6.1.
