### ISSUE TITLE
Different column sizes according to device

### ISSUE THREAD

**Issue by Aaarrrgggh** [Spiderpig86/Cirrus#52]
I would like to display columns with different sizes according to device.

For example: 

```
<section class="row">
<div class="col-lg-4 col-xs-12">
    Small column on desktop<br />
    Big column on smartphone
</div>
</section>
```

On any device, the width column is equal to 100%. How can I fix this?

Thanks,

Sincerely, 

Alexander

**Comment by Spiderpig86** [comment]
Resolved with release of 0.6.1.
