### ISSUE TITLE
documention u-hide- should be u-none=*

### ISSUE THREAD

**Issue by Karadox** [Spiderpig86/Cirrus#54]
**Describe the bug**
In the documentation part [https://cirrus-ui.netlify.app/fundamentals/viewports#breakpoints](https://cirrus-ui.netlify.app/fundamentals/viewports#breakpoints)
the part about u-none-* has a table with the convetion written out but with u-hide-* as class, this should be u-none-*

**To Reproduce**
read: [https://cirrus-ui.netlify.app/fundamentals/viewports#breakpoints](https://cirrus-ui.netlify.app/fundamentals/viewports#breakpoints)

**Comment by Spiderpig86** [comment]
Nice catch!

This has been fixed with e3b8b3723e712b754df12aa97053ffe347a00cb4.
