### ISSUE TITLE
Support for HTML progress element

### ISSUE THREAD

**Issue by DavidMonk00** [Spiderpig86/Cirrus#55]
I've just started to use this library for one of my projects and I am really impressed with it. On one web page I would like to include a progress bar to indicate the progress of an internal process.

Currently I am using a `<progress>` HTML tag for the bar, however there does not seem to be any support for the tag within the library. Is this something that may be added in the future? Or could you suggest an alternative method for displaying/styling a progress bar within the Cirrus library?

**Comment by Spiderpig86** [comment]
As of now, Cirrus does not support custom styling for `progress`. However, I do plan to work on some unique styling for it the next few updates as part of the new "Experimental" components I will be adding.

The `progress` tag works as expected using default browser/system styling if you run it inside the playground.

```
<label for="file">Downloading progress:</label>
<progress id="file" value="32" max="100"> 32% </progress>
```

https://cirrus-ui.netlify.app/playground
