### ISSUE TITLE
Issues compiling with gulp

### ISSUE THREAD

**Issue by ray73864** [Spiderpig86/Cirrus#56]
Downloaded a fresh copy via git using: git clone https://github.com/Spiderpig86/Cirrus cirrus

Went into the 'cirrus' directory, did an 'npm i', then once that was finished, followed up with a 'gulp compile' and I get the following error message back

```
[10:36:33] Using gulpfile ~/assets/cirrus/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Versions:
Node = v12.16.1
NodeJS = v15.8.0
NPM = 7.5.2
NPX = 7.5.2
GULP-CLI = 3.9.1
GULP (Local Version) = 4.0.2
OS = Debian 10.7

**Comment by ray73864** [comment]
Interestingly, if I download 'nvs' and use it to switch to a different node version (say 10.20.1), 'gulp compile' works fine.

**Comment by Spiderpig86** [comment]
Glad you found a solution. Did some quick [searching](https://stackoverflow.com/questions/38719999/cannot-read-property-apply-of-undefined-gulp) and it seems Gulp 4.x.x may have broken something.

I will check it out myself on a fresh system updating `package.json` with the right versions if needed.
