### ISSUE TITLE
Modal doesn't work as the docs.

### ISSUE THREAD

**Issue by miguel-krasamo** [Spiderpig86/Cirrus#57]
I might be doing something wrong, but I tried to copy and paste the code for the modal example,
it triggers but it doesn't show the modal like in the docs page.

It stays at the left side of the page, the overlay looks gray with full opacity and I can see the right side
of the page like the modal never showed up.

I'm using react.js

Here's a snippet of the component where I'm trying to display the modal:

```
<div className="col u-clear-right level">
          <ModalPEM />
          <a href="#modal-id">
            <button type="button" className="btn-small btn-info btn-animated level" style={{ marginRight: '15px' }}>
              <i
                className="fa-wrapper fas fa-key pad-right"
                style={{ fontSize: '14px', transform: 'rotate(135deg)' }}
              />
              <span className="level-item">ModalButton</span>
            </button>
          </a>
          <button type="button" className="btn-small btn-dark btn-animated level">
            <span className="level-item">Button 2</span>
            <i className="fa-wrapper far fa-plus-square pad-left" style={{ fontSize: '14px' }} />
          </button>
</div>
```

where my <ModalPEM> component is:

```
<div className="modal" id="modal-id">
    <a href="#target" className="modal-overlay close-btn" aria-label="Close" />
    <div className="modal-content" role="document">
      <div className="modal-header">
        <a href="#components" className="pull-right" aria-label="Close">
          <span className="icon">
            <i className="fa fa-wrapper fa-times" />
          </span>
        </a>
        <div className="modal-title">Modal Dialog</div>
      </div>
      <div className="modal-body">-- Modal content --</div>
      <div className="modal-footer">-- Rows, buttons, etc... --</div>
    </div>
  </div>
```

Result image attached.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/77803491/107700599-52280b80-6c7d-11eb-9af8-7dfe2c77e8e1.png">

**Comment by miguel-krasamo** [comment]
I was able to fix it using inline styles:

Here the lines I used:
```
<div className="modal" style={{ maxWidth: '100vw', background: 'none' }}>
    ...
    <div className="modal-content" role="document" style={{ width: '100%' }}></div>
    ...
</div>
```

**Comment by Spiderpig86** [comment]
I believe that this may happen. The modal will only cover the parent container which has `position: relative`. If none of the parent elements do for example, then the modal should correctly cover the whole screen. However, it probably didn't since it will fill the parent with relative position.

Also for setting width, feel free to try out the helper classes like `w-100`. Glad you figured out the issue. 🙂
