### ISSUE TITLE
https://unpkg.com/cirrus-ui points to v0.6.1, but docs are still using 0.6.0?

### ISSUE THREAD

**Issue by EttinCon** [Spiderpig86/Cirrus#58]
Hi! We love this framework! During the update of our site to match the latest version, we have been having trouble with the disparity between the docs and the supported classes - could you please advise if ".ignore-screen" is meant to be missing from 0.6.1, and that we should refactor our code accordingly?

Thanks! There are a few other issues but this is the one really need help with. Thanks!

PS: The docs at https://cirrus-ui.netlify.app/layout/columns#viewports which describe .ignore-screen are our reference.

**Comment by Spiderpig86** [comment]
Hi EttinCon!

Glad you enjoy the framework and apologies for the confusion. Yes, as of 0.6.1, `ignore-screen` is no longer supported as the same behavior can be re-created using `u-flex col-xs-*`. By the next version, I will probably remove this section of the documentation just to avoid the confusion.

**Comment by EttinCon** [comment]
Thanks! Will update accordingly.

**Comment by Spiderpig86** [comment]
Awesome, closing this issue.
