### ISSUE TITLE
Dropdown don't work in tiles with Firefox

### ISSUE THREAD

**Issue by Aaarrrgggh** [Spiderpig86/Cirrus#61]
Dropdown menus don't seem to work in Firefox when they are located in tiles. This is working well with Google Chrome.

Example, with Firefox: https://cirrus-ui.netlify.app/components/tiles#tiles

Thanks

**Comment by Spiderpig86** [comment]
Thanks for the feedback. Is it possible to post a screenshot from your end. I am unable to reproduce the issue and I tested it on Firefox 88. The behavior looks as expected.

![image](https://user-images.githubusercontent.com/2801187/116667337-ecc8ea00-a950-11eb-9d01-9bdfa9ea7294.png)
