### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Randerspl** [Spiderpig86/Cirrus#63]
**Describe the bug**
On documentation page: [Cirrus - Flexbox](https://cirrus-ui.netlify.app/utils/flexbox#justify) html example for flex center  should have class "u-justify-center" instead of "u-justify-flex-center"

**To Reproduce**
Enter page [Cirrus - Flexbox](https://cirrus-ui.netlify.app/utils/flexbox#justify) and scroll to Center example
![flexbox-center](https://user-images.githubusercontent.com/9450923/122752240-f9065f00-d290-11eb-8262-55d53f20308a.png)

**Comment by Spiderpig86** [comment]
Good catch! Fixing now.

**Comment by Spiderpig86** [comment]
Fixed with f3efaddca92cc01bb6105e065a944846e8f1440b. Closing.
