### ISSUE TITLE
Documentation error - Space-between and Space-around

### ISSUE THREAD

**Issue by Randerspl** [Spiderpig86/Cirrus#66]
**Describe the bug**
Hello. Again i found a mistake in documentation.
In Space-around and Space-evenly text with red background shows wrong class example of _u-justify-space-between_ instead of _u-justify-space-around_ or _u-justify-space-evenly_

**To Reproduce**
Enter page Cirrus - Flexbox and scroll to [Justify](https://cirrus-ui.netlify.app/utils/flexbox#justify)
![image](https://user-images.githubusercontent.com/9450923/124903865-b066d980-dfe4-11eb-9465-aaec9aad4bb0.png)

**Comment by Spiderpig86** [comment]
Thanks for the report! It has been fixed with 379402a9434ecd0f95cc80c64f35c39445168788.
