### ISSUE TITLE
Feature request: additional tag sizes

### ISSUE THREAD

**Issue by mikey186** [Spiderpig86/Cirrus#69]
I had switched to Cirrus from Sematic because of it's beautiful CSS-only framework. Although I do miss some of the elements that are exclusive to Sematic UI, especially the tags. 

In [Sematic UI](https://semantic-ui.com/elements/label.html), there are customizable in many sizes.
![Snipaste_2021-07-28_00-38-36](https://user-images.githubusercontent.com/5152724/127283265-be8ca90d-5440-4412-9833-4eba58c66738.png)

Unfortunately in Cirrus, there's only......three. Small (normal), medium, and extra large. I can try to use the `h1` tag, but the whole element would go out of whack. I can try to override with the css, but I don't wanna break it either. 

I would love to see many more sizes of the tags.

**Comment by Spiderpig86** [comment]
Thanks for the suggestion! I think that'll be a great addition to Cirrus. Currently deliberating how I can split the builds between `core` and `ext`. That'll affect which build this feature will be included in. In the mean time, I'll decide which roadmap this feature will be a part of.

**Comment by mikey186** [comment]
Thank you. When you can, you should look into the '[label](https://semantic-ui.com/elements/label.html)' section in Semantic UI. I would love to see much of these label elements into Cirrus as well. Like image in a label, pointing labels, corner labels, 'price tag' shaped labels, attached in a card label, as well as floating labels (used for unread messages counter).

**Comment by Spiderpig86** [comment]
Resolved as of 0.6.3 release. Closing.
