### ISSUE TITLE
AMP compatibility?

### ISSUE THREAD

**Issue by niutech** [Spiderpig86/Cirrus#7]
I like your Cirrus framework. However, is it possible to use it in AMP pages?

AMP requires a stylesheet to fit in 50KB and cannot include `!important`. It also should not depend on JS, interactions should be in pure CSS.

How much work would it take to make Cirrus AMP-compatible?

**Comment by Spiderpig86** [comment]
This is something I will look into. I'm already trying to see if I could limit the use of `!important`. To achieve `50KB`, I may consider creating a `core` version which only includes the main styles that covers most of what would be needed and exclude external features. More info on this update will be released in the near future.

**Comment by niutech** [comment]
@Spiderpig86 Any news on this?

**Comment by Spiderpig86** [comment]
Hi @niutech 

Based on the current roadmap for Cirrus and the restrictions imposed by [AMP](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages/) itself, it doesn't make much sense to make the regular version of Cirrus AMP compatible. A separate version of Cirrus should be developed that adheres to the AMP requirements and I currently do not have the bandwidth for it as of now.

**Comment by niutech** [comment]
Actually, when I remove the `!important` from [cirrus-core.min.css](https://github.com/Spiderpig86/Cirrus/blob/master/dist/cirrus-core.min.css), it passes AMP validation.
