### ISSUE TITLE
Header layout bug at 768px breakpoint

### ISSUE THREAD

**Issue by mjhouse** [Spiderpig86/Cirrus#70]
**Describe the bug**
At a width of 768px, header nav transitions to vertical before the hamburger menu is visible.

![image](https://user-images.githubusercontent.com/4141157/129381450-ea8b23b4-030a-424e-87a5-7f2b1d70ede0.png)

**To Reproduce**

1. Using Cirrus 0.6.2-patch-1
2. Create a layout with the following html.

```html
    <div class="header header-fixed u-unselectable header-animated">
        <div class="header-brand">
            <div class="nav-item no-hover">
                <a href="/"><h6 class="title">Title</h6></a>
            </div>
            <div class="nav-item nav-btn" id="header-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="header-nav" id="header-menu">
            <div class="nav-right">
                <div class="nav-item">
                    <a href="!#">Overview</a>
                </div>
                <div class="nav-item">
                    <a href="!#">Profiles</a>
                </div>
                <div class="nav-item">
                    <a href="!#">Information</a>
                </div>
                <div class="nav-item">
                    <a href="!#">Logout</a>
                </div>
            </div>
        </div>
    </div>
```
Resize the page.

**Solution**

On line 2198 of the generated css file, I changed `@media screen and (min-width: 769px)` to `@media screen and (min-width: 768px)`

**Comment by Spiderpig86** [comment]
Thanks for the report! Will look into it.

**Comment by Spiderpig86** [comment]
Issue should be fixed! I tested this out on the [Playground](https://cirrus-ui.netlify.app/playground) and works as expected.

**Comment by mjhouse** [comment]
Awesome, thanks man. Should I close this or leave it for you?

**Comment by Spiderpig86** [comment]
I can close it. Again, thanks for the report!
