### ISSUE TITLE
Wrong code example for Disabled Button

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#75]
The given code example is not for disabled button.

![image](https://user-images.githubusercontent.com/7860859/135770716-45172f0a-0c60-4d2d-95a1-d1002d8967d0.png)

**Comment by Spiderpig86** [comment]
Thanks for the report! I will update the docs for this.

**Comment by Spiderpig86** [comment]
Fixed in fbe2e26a62f548f35599ec9cb8b861d717e99647.
