### ISSUE TITLE
Feature: more utils css classes

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#78]
**Is your feature request related to a problem ?**
I am using this framework in different projects, one **Vue** project and 2 using **Svelte**, one common thing missing in these 3 projects is more utils css classes.
I copy paste the same code on these different projects, which is not the best solution, and it will be very usefully and helpful to have these in the same main ui framework.

**Describe the solution you'd like**
> PS:
>> **0-100** means **0-10-20-30-40-50-60-70-80-90-100**
>> **xs-xl** means **xs-sm-md-lg-xl**
>> **100-900** means **100-200-300-400-500-600-700-800-900**
#### 1. Square border 
**syntax:** `u-square`
It's the inverse of u-round, it would remove the border-radius of an element

#### 2. Min/Max for height and width
**syntax:** `u-(h/w)-(min/max)-((0-100)/screen)` OR `u-(min/max)-(h/w)-((0-100)/screen)` to be aligned with CSS
This will allow to define for example the min-height of the body

### 3. Z-index
**syntax:** `u-z-((0-100)/auto)`

### 4. Font size
**syntax:** `u-text-((h1-h6)/(xs-xl)/base)`

### 5. Shadow
**syntax:** `u-shadow-(none/(xs-xl))` or `u-shadow-(0-12)` for more options

### 6. Colors without -(100-900)
**syntax:** `u-(red,blue,indigo,etc....)`
This would be helpful when all you need is just a regular red for example, which should be the middle red of the list **red-500**

I would be very happy to create PR for each of these features, just let me know if they go with what you are planning for your framework.

**Comment by Spiderpig86** [comment]
Hey!

Just wanted to update this issue on the progress on the suggested items for 0.7.0.

**1. Square Border**

- Will be available as `u-round-none`.

**2. Min/Max for Height and Width**

- Item is already completed. Will be similar in syntax, but without the `u-` prefix.

**3. Z-index**

- Completed.

**4. Font-Size**

- Completed, there is only the xs. sm, md, lg, and xl variants. You can add more in the new config based class generation I'm adding in for 0.7.0 if you need more sizes.

**5. Shadow**

- Completed with none and xs-xl. Also config based so you can modify it and build your own version if needed.

**6. Colors without (100-900)**

- This I won't pick up. You can treat 500 as the default color for all shades. There are also the more semantic versions of colors from the earlier releases of Cirrus.

There are also a bunch of stuff coming in for the next release so stay tuned. :)

**Comment by roonie007** [comment]
@Spiderpig86 Perfect !!! thanks for the update 😄
