### ISSUE TITLE
SCSS/PostCSS version?

### ISSUE THREAD

**Issue by venelinn** [Spiderpig86/Cirrus#8]
Is there a way to get the real source of the files for easy customization? Thanks !

**Comment by Spiderpig86** [comment]
Currently that is planned for a future major release (1.0.0 as of now). For 0.5.5, I will be introducing `themes.css` to make changing the colors in Cirrus easier so be on the lookout.

**Comment by dolcy** [comment]
Cirrus is very well done; better than Bulma imo. Check out [Turretcss](https://turretcss.com/) for a well-integrated PostCSS implementation as reference. Also, a Vue version would be awesome!

**Comment by Spiderpig86** [comment]
Thanks for the feedback! I will check that out. First I will need to get out the main updates for 0.5.5, and 1.0.0 will just polish the changes along with bringing a Sass variant and see what I could do in terms of bringing Cirrus to frameworks.

**Comment by hcatlin** [comment]
Would love this for Sass!

**Comment by Spiderpig86** [comment]
> Would love this for Sass!

100% agree. Thanks for checking out the project 😄 

Just an update on this issue. I have already started the preliminary work on porting Cirrus over the Sass. What's left is going through each file and rewriting it such that it takes advantage of most of Sass's features. Corresponding issue card is [here](https://github.com/Spiderpig86/Cirrus/projects/4#card-39630388).

**Comment by hcatlin** [comment]
I'd recommend trying out the new Dart-Sass as a compiler... it has features not yet implemented in Node-Sass such as modules that can be really powerful for something like this.

https://css-tricks.com/introducing-sass-modules/

**Comment by Spiderpig86** [comment]
Closing since this was launched with 0.6.0.
