### ISSUE TITLE
Chore: Remove the double hyphen in some classes

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#80]
**Is your feature request related to a problem? Please describe.**
Some classes have double hyphen example `btn--circle` `btn--pilled`  `tag--info` `form-ext-input--error` etc...

**Describe the solution you'd like**
Remove the double hyphen

**Comment by Spiderpig86** [comment]
Thanks for the suggestion! I think the double hyphen should stay to work as part of the BEM convention. This is to help specify the modifiers that appear for those classes. http://getbem.com/naming/
