### ISSUE TITLE
Feature: Support <a> tag for button

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#81]
**Is your feature request related to a problem? Please describe.**
If we want to create a button that is a link we have to nest a `<button>` inside an `<a>` tag while instead of that we can simply attribute the `btn` class to the `<a>` tag but unfortunately it's not supported since the `<a>` tag style override some of the btn class properties.

![image](https://user-images.githubusercontent.com/7860859/136055437-4132a006-57af-4742-9375-fc432440d813.png)

**Describe the solution you'd like**
Maybe add **:not(.btn)** in https://github.com/Spiderpig86/Cirrus/blob/master/src/core/links.scss

**Comment by roonie007** [comment]
@Spiderpig86 I think this issue can be closed this since it has been merged with the v0.7.0.

But you should add the button using `<a>` tag as an example here
![image](https://user-images.githubusercontent.com/7860859/162650511-363aee82-6cdb-4dfb-9467-fa08bb96d139.png)

**Comment by Spiderpig86** [comment]
Added to docs, closing.
