### ISSUE TITLE
Chore: rename size modifiers

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#82]
**Is your feature request related to a problem? Please describe.**
In classes it always better to have short classes names and I personally find the `-xsmall` `-small` `-large` `-xlarge` a little bit long.
 
**Describe the solution you'd like**
Why not just rename them `xs` `sm` `lg` `xl` ?

**Comment by Spiderpig86** [comment]
Agree with this change. The util classes already use the shortened version of these names and they should be standardized. Added to roadmap.
