### ISSUE TITLE
Grid stack at certain screen size

### ISSUE THREAD

**Issue by Ponkhy** [Spiderpig86/Cirrus#89]
Hello,

is it possible to have a grid stack at a certain screen sizes, or would it be possible to have a different col size in a row for sm/md/lg/xl?
Because i would like to build kind of a gallery, but stack automatically depending on the screen size, or only show a certain amount of cols/images per row.

Thanks!

**Comment by Spiderpig86** [comment]
Hey!

Thanks for the suggestion! I think what you are looking for is already handled in this change here: https://github.com/Spiderpig86/Cirrus/commit/decb89708ef49ccfe4d3a0c5bd8cdeea2c4fffdd

This adds viewport support for all grid classes, so you can do something like `grid-md`.

**Comment by Ponkhy** [comment]
Ohh Yea, it does, looking really forward to it! Thank you
