### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by equinusocio** [Spiderpig86/Cirrus#9]
Hi! I'm **Mattia Astorino** :D can i ask where you picked my name? 

<img width="968" alt="screen shot 2018-07-04 at 17 06 57" src="https://user-images.githubusercontent.com/10454741/42284467-e1422212-7fac-11e8-8f8a-0e62a4b9c871.png">

**Comment by Spiderpig86** [comment]
To be quite frank, I actually forgot where I picked your name. I will remove it right away.

**Comment by equinusocio** [comment]
You get the text here :)
https://codepen.io/equinusocio/pen/VYWxXy

**Comment by Spiderpig86** [comment]
I remember now. I hope you don't mind if I use that as placeholder text :)
