### ISSUE TITLE
Patreon not working

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#94]
**PS: I did not find a way to contact you directly, so I opened an Issue.**

Your patreon is not working https://www.patreon.com/spiderpig86/creators .
Maybe you should activate it so you can get some sponsors for your project.

Looking forward for the next BIG update 😄

**Comment by Spiderpig86** [comment]
Hey @roonie007!

Thanks for letting me know! I have republished the page so the donation tiers should be visible now.

I am very excited for the launch of 0.7.0. There was quite a lot of work and refactoring that gone into this version and I hope it will be easier for users to use and customize their builds.
